import test from 'node:test';import assert from 'node:assert/strict';import{detectFormat,zipEntries,TARGETS,conversionNote,outputName}from'../public/assets/document-format-core.js';
const text=s=>new TextEncoder().encode(s);
function central(name,size=100){const n=text(name),b=new Uint8Array(46+n.length+1),v=new DataView(b.buffer);v.setUint32(0,0x02014b50,true);v.setUint32(24,size,true);v.setUint16(28,n.length,true);b.set(n,46);return b}
function archive(name){const b=central(name),all=new Uint8Array(b.length+4);all.set([80,75,3,4]);all.set(b,4);return all}
test('binary signatures override misleading extensions',()=>{assert.equal(detectFormat(text('%PDF-1.7 hello'),'invoice.docx').type,'pdf');assert.equal(detectFormat(new Uint8Array([137,80,78,71,13,10]),'pic.txt').type,'png');assert.equal(detectFormat(new Uint8Array([255,216,255]),'pdf.pdf').type,'jpg')});
test('Office formats are detected using archive members',()=>{assert.equal(detectFormat(archive('word/document.xml'),'wrong.zip').type,'docx');assert.equal(detectFormat(archive('xl/workbook.xml'),'wrong.docx').type,'xlsx');assert.equal(detectFormat(archive('ppt/presentation.xml'),'wrong.pdf').type,'pptx')});
test('archive expansion and truncated directory entries are rejected',()=>{assert.throws(()=>zipEntries(central('word/document.xml',101*1024*1024)),/100 MB/);const b=central('word/document.xml');assert.throws(()=>zipEntries(b.slice(0,-3)),/incomplete/)});
test('text detection distinguishes markup while preserving explicit text ambiguity',()=>{assert.equal(detectFormat(text('<html><body>Hello</body></html>'),'report.txt').type,'html');assert.equal(detectFormat(text('a,b\n1,2'),'table.csv').type,'csv');assert.match(detectFormat(text('# title'),'notes.md').basis,/no unique signature/);assert.equal(detectFormat(new Uint8Array([0,200,201]),'text.txt').type,'unknown')});
test('unsupported conversions are not advertised and fidelity is explicit',()=>{assert.equal(TARGETS.pptx,undefined);assert.ok(!TARGETS.pdf.includes('xlsx'));assert.match(conversionNote('pdf','docx'),/NOT editable/);assert.match(conversionNote('xlsx','csv'),/selected worksheet only/);assert.equal(outputName('My report.PDF','docx'),'My-report-converted.docx')});
