const studioLink = '<a class="btn" href="https://www.brandique.in" target="_blank" rel="noopener noreferrer">Explore BrandiQue Web Solutions ↗</a>';
const services = [
 ['01','Website design & development','A strong first impression, built around your business. Clear page layouts, thoughtful user journeys and responsive websites help visitors understand what you offer and take the next step.'],
 ['02','Branding & visual identity','Give your business a recognisable voice and visual direction. Consistent colours, typography and design bring your story together across your digital presence.'],
 ['03','SEO & online visibility','Make your website easier to discover and understand. Search-friendly structure, useful content and technical foundations support sustainable visibility as your business grows.'],
 ['04','E-commerce experiences','Turn product discovery into a clear shopping journey. Well-organised catalogues and considered storefront design help customers explore your products with confidence.'],
 ['05','AI automation','Explore practical ways to reduce repetitive work. Purpose-built digital workflows can help your team spend more time on customers, ideas and meaningful business decisions.'],
 ['06','Chatbots & digital assistance','Make everyday questions easier to answer. Conversational experiences can guide visitors, explain your services and help people find their next step.']
];
export const about = `<div class="company-page wrap">
<section class="company-hero"><div><span class="eyebrow">THE PEOPLE BEHIND THE TOOLS</span><h1>Thoughtful design.<br><em>Everyday possibility.</em></h1><p class="company-intro">BrandiQue Tools brings useful digital tasks into one simple place. Behind it is BrandiQue Web Solutions — connecting design, technology and practical ideas to help brands build their presence online.</p><div class="company-actions">${studioLink}<a class="text-link" href="/tools/">Try our free tools →</a></div></div><aside class="company-vision"><span class="eyebrow">OUR VISION</span><h2>Make digital feel<br>simple. And useful.</h2><p>We believe a great digital experience should look considered, feel easy to use and serve a clear purpose. Our ambition is to make that experience accessible to businesses, creators and people getting things done.</p><span class="company-signature">BrandiQue Web Solutions</span></aside></section>
<section class="company-section"><span class="eyebrow">MEET BRANDIQUE</span><h2>A creative partner for your digital presence.</h2><div class="company-columns"><p>BrandiQue Web Solutions brings together website development, design, branding, SEO, e-commerce, AI automation and chatbots. From the way a brand looks to the way its website works, the focus is on creating a connected experience that makes sense to the people using it.</p><p>Our mission is to turn ideas into clear, purposeful digital experiences. Whether you are introducing a new business, refreshing an existing website or exploring smarter workflows, BrandiQue is a place to start the conversation and shape the right direction for your project.</p></div></section>
<section class="company-section"><span class="eyebrow">WHAT WE PROVIDE</span><h2>Creative thinking. Practical digital solutions.</h2><p class="company-section-intro">Explore the services available through BrandiQue Web Solutions. Visit the official website to discuss your goals, scope and project requirements.</p><div class="company-services">${services.map(([n,t,p])=>`<article class="company-service"><span class="company-number">${n}</span><h3>${t}</h3><p>${p}</p></article>`).join('')}</div></section>
<section class="company-section company-values"><div><span class="eyebrow">WHAT GUIDES US</span><h2>Good design earns its place.</h2><p>Visual quality matters. So do clear words, useful features and the small details that help someone move forward. These principles shape the experience we aim to create.</p></div><div class="company-principles"><article><h3>Clarity before complexity</h3><p>Help people understand what to do next, with straightforward content and purposeful layouts.</p></article><article><h3>A consistent brand experience</h3><p>Connect identity, interface and messaging so every part of a website feels like it belongs together.</p></article><article><h3>Technology with a purpose</h3><p>Choose features for the problems they solve, with usability at the heart of the experience.</p></article></div></section>
<section class="company-section"><span class="eyebrow">WHY WE BUILT BRANDIQUE TOOLS</span><h2>Less busywork. More room for your ideas.</h2><p class="company-section-intro">Resizing an image, organising a PDF or checking a piece of text should not interrupt your day. BrandiQue Tools puts focused browser utilities within reach of students, creators, professionals and small businesses.</p><div class="company-benefits"><article><h3>Open and get started</h3><p>Use the tools without creating an account or signing in.</p></article><article><h3>Local file processing</h3><p>Supported file operations run in your browser. Page assets and advertising still use network requests.</p></article><article><h3>Free everyday utilities</h3><p>Explore tools for images, PDFs, documents, video, calculations and more.</p></article></div><p>Every browser and file is different. Keep your originals and check your downloads before using them. Read our <a href="/privacy/">Privacy Policy</a> and <a href="/terms/">Terms of Use</a> for the details.</p></section>
<section class="company-cta"><span class="eyebrow">YOUR NEXT CHAPTER</span><h2>Have an idea for your business?<br>Let’s give it a digital home.</h2><p>Discover BrandiQue Web Solutions and start a conversation about your website, brand or next digital project.</p>${studioLink}</section></div>`;
const policy = (title,intro,sections) => `<article class="section wrap legal policy-page"><span class="eyebrow">TRUST & TRANSPARENCY</span><h1>${title}</h1><p class="lead">${intro}</p><p class="policy-date">Last updated: 19 September 2026</p>${sections.map(([h,p])=>`<section><h2>${h}</h2>${p}</section>`).join('')}</article>`;
export const privacy = policy('Privacy Policy','Understand how BrandiQue Tools handles your files, browser data and visits to this website.',[
 ['About this policy','<p>This policy applies to tools.brandique.in, a browser-tool website built by BrandiQue Web Solutions. The separate brandique.in website and external services have their own policies.</p>'],
 ['Your files and tool inputs','<p>Our tools are designed to process selected files and entered content locally in your browser, rather than upload them to a BrandiQue conversion server. No account is required to use the tools. Selecting a file gives the current tool access to that file for the operation you request.</p><p>Local processing does not mean the entire page is offline: hosting, scripts, fonts, optional processing libraries and advertisements may involve network connections.</p>'],
 ['Browser storage and downloads','<p>A tool may use browser memory, cached resources or local browser storage for its operation or preferences. Storage behaviour varies by tool and browser. Downloaded results are saved to the location you choose and remain on your device until you remove them.</p><p>You can clear this website’s stored data through your browser settings. Doing so may reset preferences or remove locally retained work. Keep a separate copy of files you need.</p>'],
 ['Website delivery and technical information','<p>Hosting and content-delivery providers may receive technical request information such as an IP address, browser type, requested URL and request time to deliver and protect the website. External library providers also receive the requests needed to load their resources. These requests are separate from local file processing.</p>'],
 ['Your privacy choices','<p>You control which files and text you give a tool. You can close the page, clear site data and manage cookies through your browser. Avoid entering information you do not have permission to process. On shared devices, remove downloaded files and stored browser data when appropriate.</p>'],
 ['External links and contacting us','<p>If you follow an external link or advertisement, the destination’s privacy practices apply. If you contact BrandiQue through its official website, the information you choose to submit is handled through that contact channel; it is not part of a local tool conversion.</p><p>For questions about this policy or a privacy request, use the contact options at <a href="https://www.brandique.in" target="_blank" rel="noopener noreferrer">BrandiQue Web Solutions</a>. Describe the relevant page and concern without attaching sensitive documents unnecessarily.</p>'],
 ['Security and policy updates','<p>Local processing reduces the need to send document contents to a conversion server, but no website or device can promise absolute security. Use an updated browser and keep important originals. We may revise this policy as the website changes; the update date above identifies the current version.</p>']
]);
export const terms = policy('Terms of Use','Please use BrandiQue Tools responsibly and review the results of every operation.',[
 ['Using the website','<p>These terms apply to your use of BrandiQue Tools at tools.brandique.in. By using the website, you agree to these terms. If you do not agree, please stop using it. The browser tools are provided without an account and are currently free to use.</p>'],
 ['Your content and permissions','<p>Your files and entered content remain yours. You are responsible for having the rights and permissions needed to process them, including any personal information belonging to other people. Using a tool does not transfer ownership of your content to BrandiQue.</p>'],
 ['Acceptable use','<p>Use the website lawfully. Do not use it to infringe intellectual property, invade someone’s privacy, distribute harmful material or interfere with the service. Do not attempt to bypass security measures, introduce malicious code or misuse advertising placements.</p>'],
 ['Outputs, compatibility and backups','<p>Tool results depend on the input file, chosen settings and browser capabilities. Large files, unsupported codecs, encrypted documents, fonts and complex layouts may affect processing or output quality. A conversion may not preserve every element of the original.</p><p>Keep your original files and inspect the downloaded result before relying on it, sharing it or deleting the source. Processing may be interrupted if you close the page, run out of memory or lose access to a required resource.</p>'],
 ['Calculators, resume checks and other guidance','<p>Calculations, estimates, formatting checks and resume ATS scores are informational aids. They are not professional financial, legal, medical or employment advice. A resume score does not guarantee compatibility with every recruitment system, an interview or a job offer. Independently verify results used for important decisions.</p>'],
 ['Availability and responsibility','<p>We aim to provide useful tools, but availability, error-free operation and suitability for every purpose are not guaranteed. Features may be updated, replaced or removed. To the extent permitted by applicable law, the tools are provided as available, and BrandiQue is not responsible for losses resulting from reliance on incorrect outputs, interruptions or lost local work. Nothing in these terms excludes rights or responsibilities that cannot lawfully be excluded.</p>'],
 ['Advertising and third-party services','<p>Advertisements help support the website. An advertisement or external link is not an endorsement of the advertiser, product or destination. Third-party websites, software libraries and services may have their own terms and privacy practices. Any purchase or agreement you make with another provider is between you and that provider.</p>'],
 ['Website identity and separate services','<p>BrandiQue branding and website materials are distinct from the files you process. Do not present yourself as BrandiQue or imply an endorsement without permission. Custom website, branding or automation work offered through BrandiQue Web Solutions is separate from these free tools and subject to the scope and terms agreed for that project.</p>'],
 ['Updates and contact','<p>These terms may change as the service evolves. Check the date above for the current version. For questions, feedback or a report about misuse, visit <a href="https://www.brandique.in" target="_blank" rel="noopener noreferrer">BrandiQue Web Solutions</a> and use the available contact options. For information about data handling, read our <a href="/privacy/">Privacy Policy</a>.</p>']
]);
