import {access,readFile,readdir} from 'node:fs/promises';
import {tools,legal} from '../src/tools.mjs';

const exists=path=>access(path).then(()=>true,()=>false);
const htmlFiles=[];
const walkHtml=async dir=>{
 for(const entry of await readdir(dir,{withFileTypes:true})){
  const path=`${dir}/${entry.name}`;
  if(entry.isDirectory())await walkHtml(path);
  else if(path.endsWith('.html'))htmlFiles.push(path);
 }
};
const routeFile=pathname=>pathname==='/'?'dist/index.html':pathname.endsWith('/')?`dist${pathname}index.html`:`dist${pathname}`;
const expectedRoutes=['/','/tools/',...tools.map(tool=>`/tools/${tool.slug}/`),...legal.map(([slug])=>`/${slug}/`)];
for(const route of expectedRoutes)if(!await exists(routeFile(route)))throw new Error(`Missing generated route: ${route}`);

const overrideSource=await readFile('scripts/overrides.mjs','utf8');
for(const tool of tools){
 if(tool.slug==='pdf-editor')continue;
 if(!overrideSource.includes(`'${tool.slug}'`))throw new Error(`Upgraded route is not generated by overrides.mjs: ${tool.slug}`);
}

await walkHtml('dist');
const broken=[];
for(const file of htmlFiles){
 const html=await readFile(file,'utf8');
 for(const marker of ['class="site-header"','class="site-footer"']){
  if(html.split(marker).length!==2)throw new Error(`Missing or duplicate shell ${marker}: ${file}`);
 }

 if((html.match(/class="site-trust"/g)||[]).length!==1)throw new Error(`Missing or duplicate trust strip: ${file}`);
 if(!/href="\/assets\/release-[a-f0-9]{16}\/presentation\.css"/.test(html))throw new Error(`Missing presentation stylesheet: ${file}`);
 if(!html.includes('href="https://www.brandique.in" target="_blank" rel="noopener noreferrer"'))throw new Error(`Missing safe brand link: ${file}`);
 if(!/src="\/assets\/release-[a-f0-9]{16}\/site-shell\.js"/.test(html))throw new Error(`Unversioned site shell: ${file}`);
 const slug=html.match(/rel="canonical" href="https:\/\/[^/]+\/tools\/([^/]+)\//)?.[1];
 if(tools.some(tool=>tool.slug===slug)){
  const related=html.match(/<section class="section wrap related-tools"[\s\S]*?<\/section>/g)||[];
  if(related.length!==1)throw new Error(`Missing or duplicate recommendations: ${file}`);
  if(!related[0].includes('class="card"'))throw new Error(`Empty recommendations: ${file}`);
  if(related[0].includes(`href="/tools/${slug}/"`))throw new Error(`Tool recommends itself: ${file}`);
 }

 for(const match of html.matchAll(/(?:href|src)=["'](\/[^"'#?]*)/g)){
  const url=match[1];
  const target=url==='/'?'dist/index.html':url.endsWith('/')?`dist${url}index.html`:`dist${url}`;
  if(!await exists(target))broken.push(`${file} -> ${url}`);
 }
}
if(broken.length)throw new Error(`Broken local links/assets:\n${broken.join('\n')}`);
console.log(`QA passed for ${expectedRoutes.length} routes and ${htmlFiles.length} HTML files`);

// Validate lazy CSS, module imports and Worker paths inside the release, not only HTML links.
const releaseDirs=(await readdir('dist/assets')).filter(name=>/^release-[a-f0-9]{16}$/.test(name));
if(releaseDirs.length!==1)throw new Error('Expected one content-versioned asset release');
const release=`/assets/${releaseDirs[0]}/`;
for(const name of await readdir(`dist${release}`)){
 if(!name.endsWith('.js'))continue;
 const js=await readFile(`dist${release}${name}`,'utf8');
 for(const match of js.matchAll(/["'](\/assets\/[^"']+)["']/g)){
  if(!match[1].startsWith(release)||!await exists(`dist${match[1]}`))throw new Error(`Invalid lazy asset in ${name}: ${match[1]}`);
 }
 for(const match of js.matchAll(/(?:from\s*|import\s*\()["'](\.\/[^"']+)["']/g)){
  if(!await exists(`dist${release}${match[1].slice(2)}`))throw new Error(`Missing relative import in ${name}: ${match[1]}`);
 }
}
console.log('Versioned lazy styles, imports and Worker URLs passed');
